### ISSUE TITLE
So after i updated to v5.0.0 the disenchant cost has channged

### ISSUE THREAD

**Issue by FearlessNite345** [H7KZ/Disenchantment#10]
so on 4.0.0 it costed 15 for 

Base Value: 10
Enchantments: Unbreaking (level 3), Repairing (level 2), Thrive (level 1)
Multiplication Factor: 0.25

but on 5.0.0 it now costs 17 has something changed?

i didnt change the config values

**Comment by H7KZ** [comment]
Reviewed it, refactored it, fixed it, should be 18 xp :DDDDDD

base = 10, unbreaking = 3, repairing = 2, thrive = 1, multiplier = 0.25

Calculate:
10 + (1 * 1) = 11                 base + (thrive * multiplier)
11 + (2 * 1.25) = 13.5         base + (repairing * multiplier)
13.5 + (3 * 1.5) = 18           base + (unbreaking * multiplier)

In total 18xp


Will be fixed in v5.1.0 (also adding more custom plugin supports)

**Comment by ejm554** [comment]
@H7KZ : Could you explain more about how the multiplier works in your example where you started out by saying that the _multiplier = 0.25_ ?:

> ... **_multiplier_** = 0.25
>
> 10 + (1 * **_1_**) = 11 base + (thrive * **_multiplier_**)
> 11 + (2 * **_1.25_**) = 13.5 base + (repairing * **_multiplier_**)
> 13.5 + (3 * **_1.5_**) = 18 base + (unbreaking * **_multiplier_**)

If I'm reading this example correctly, the multipliers in the three operations are 1, then 1.25, and then 1.5. How/why are these multipliers changing by factors of 4, 5, and 6, respectively? 

When I read your list of starting values here (and in `config.yml`), it suggested to me that these were constants and shouldn't change. In other words, I would have assumed that the multiplier should _always_ be 0.25, and never vary. Clearly, I'm misunderstanding.

**Comment by H7KZ** [comment]
With each enchantment the disenchantment gets progressively more expensive due to multiplier stacking up. With each iteration the multiplier adds it self to make the next enchantment more expensive.

So with 4 enchantments the multiplier of 0.4 will, at the final enchantment, be 1.6

1. First Enchantment will be multiplied by 0.4
2. Second enchantment will be multiplied by 0.8
3. Third by 1.2
4. Fourh by 1.6

If you feel this is somehow unbalanced or confusing at counting, please say so! It is easily changeable :)
